- name: Install PHP
  apt:
    name="{{ item }}"
    state=present
  with_items:
    - php5-fpm
    - php5
    - php-pear
    - php5-mysql
  sudo: yes

- name: Create destination folder
  file:
    path: /opt/tinker/shared_files/yii_project
    state: directory
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
    mode: 0755
  sudo: yes
  sudo_user: "{{ server_user }}"

- name: Clone git yii repo
  git:
    repo: "{{ yii_git_repo }}"
    dest: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}"
    version: "{{ yii_git_version  }}"
    update: yes
    force: yes
    recursive: yes
    accept_hostkey: yes
  sudo: yes
  sudo_user: "{{ server_user }}"    
  when: yii_git_repo is defined
  tags: update_yii_repo

- name: Composer | Install
  command: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  args:
    chdir: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}"
    creates: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}/composer-setup.php"
  sudo: yes
  sudo_user: "{{ server_user }}"
  tags:
    - update_yii_repo

- name: Composer | Setup
  command: php composer-setup.php
  args:
    chdir: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}"
    creates: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}/composer.phar"
  sudo: yes
  sudo_user: "{{ server_user }}"
  tags:
    - update_yii_repo

- name: Install Yii2 dependencies 
  shell: 'php composer.phar global require "fxp/composer-asset-plugin"'
  args:
    chdir: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}"
    creates: "/home/{{ server_user }}/.composer/vendor"
  sudo: yes
  sudo_user: "{{ server_user }}"
  when: yii_git_repo is defined
  tags:
    - update_yii_repo  

- name: Update dependencies for repo. This may take a while . . . . . 
  shell: "php composer.phar update -n {{ yii_extra_flags }}"
  args:
    chdir: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}"
#    creates: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}/vendor" 
  sudo: yes
  sudo_user: "{{ server_user }}"
  when: yii_git_repo is defined
  tags: update_yii_repo

- name: Kill existing yii services
  shell: "ps aux | grep yii | grep -v grep | awk '{printf(\"%s \"), $2}' | xargs kill -9"
  sudo: yes
  sudo_user: "{{ server_user }}"
  tags:
    - update_services
    - update_yii_repo
  
- name: Run yii server
  shell: nohup php yii serve 0.0.0.0:8080 2>&1 | tee /tmp/yii.log /opt/tinker/shared_files/yii.log &
  args:
    chdir: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}"
  sudo: yes
  sudo_user: "{{ server_user }}"
  register: command_result
  tags:
    - update_services
    - update_yii_repo
    - test
  when: yii_git_repo is defined

- name: Fail if yii server failed to succeed. Verify logfile or last stdout
  fail: msg="the command failed"
  when: "'started' not in command_result.stdout"
  tags:
    - test

- name: Add cron jobs
  cron:
    name="Start yii fw"
    special_time="reboot"
    user="{{ server_user }}"
    job="cd /opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }} && nohup php yii serve 0.0.0.0:8080 > /tmp/yii.log 2>&1 &"
  sudo: yes
  sudo_user: "{{ server_user }}"
