- name: Install PHP
  apt:
    name="{{ item }}"
    state=present
  with_items:
    - php5
    - php-pear
    - php5-mysql
  sudo: yes

- name: Download basic server
  command: wget https://github.com/yiisoft/yii2/releases/download/2.0.10/yii-basic-app-2.0.10.tgz -O yii.tgz
  args:
    chdir: /tmp/
    creates: /tmp/yii.tgz
  sudo: yes
  sudo_user: "{{ server_user }}"

- name: Create destination folder
  file:
    path: /opt/tinker/shared_files/yii_project
    state: directory
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
    mode: 0755
  sudo: yes
  sudo_user: "{{ server_user }}"

- name: Unarchive yii
  unarchive:
    src=/tmp/yii.tgz
    dest=/opt/tinker/shared_files/yii_project
    copy=no
    creates=/opt/tinker/shared_files/yii_project/basic/config
  sudo: yes
  sudo_user: "{{ server_user }}"
  when: yii_git_repo is undefined

- name: Clone git yii repo
  git:
    repo: "{{ yii_git_repo }}"
    dest: /opt/tinker/shared_files/yii_project/basic/
    version: "{{ yii_git_version }}"
    update: yes
    recursive: yes
  when: yii_git_repo is defined

- name: create yii configuration
  template:
    src=web.php
    dest=/tmp/web.php
  sudo: yes
  sudo_user: "{{ server_user }}"


- name: Add yii configuration
  command: mv /tmp/web.php /opt/tinker/shared_files/yii_project/basic/config/web.php
  sudo: yes
  sudo_user: "{{ server_user }}"

- name: Run yii server
  shell: nohup php yii serve 0.0.0.0:8080 > /tmp/yii.log 2>&1 &
  args:
    chdir: /opt/tinker/shared_files/yii_project/basic
  sudo: yes
  sudo_user: "{{ server_user }}"
  tags: run_yii

- name: Add cron jobs
  cron:
    name="Start yii fw"
    special_time="reboot"
    user="{{ server_user }}"
    job="cd /opt/tinker/shared_files/yii_project/basic && nohup php yii serve 0.0.0.0:8080 > /tmp/yii.log 2>&1 &"
  sudo: yes
  sudo_user: "{{ server_user }}"
