---
- name: Create destination folder
  file:
    path: "{{ dest }}"
    state: directory
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
    mode: 0755
  sudo: yes
  sudo_user: "{{ server_user }}"

- git:
    repo: 'https://github.com/spring-guides/gs-maven.git'
    dest: "{{ dest }}"

- name: Download apache maven
  get_url:
    url: http://www-us.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
    dest: /tmp/apache-maven.tar.gz
    mode: 0440

- unarchive:
    src: /tmp/apache-maven.tar.gz
    dest: /home/vagrant/

- name: Update repositories cache and install java
  apt:
    name: default-jdk
    update_cache: yes
  sudo: yes
