- name: Install PHP
  apt:
    name="{{ item }}"
    state=present
  with_items:
    - php5-fpm
    - php5
    - php-pear
    - php5-mysql
  sudo: yes

- name: Create destination folder
  file:
    path: /opt/tinker/shared_files/yii_project
    state: directory
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
    mode: 0755
  sudo: yes
  sudo_user: "{{ server_user }}"

- name: Clone git yii repo
  git:
    repo: "{{ yii_git_repo }}"
    dest: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}"
    version: "{{ yii_git_version  }}"
    update: no
    force: yes
    recursive: yes
    accept_hostkey: yes
  sudo: yes
  sudo_user: "{{ server_user }}"    
  when: yii_git_repo is defined
  tags: update_repo

- name: create yii configuration
  template:
    src=web.php
    dest=/tmp/web.php
  sudo: yes
  sudo_user: "{{ server_user }}"
  tags: update_repo

- name: Add yii configuration
  command: "mv /tmp/web.php /opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}/config/web.php"
  sudo: yes
  sudo_user: "{{ server_user }}"
  when: yii_git_repo is defined
  tags: update_repo

- name: Composer | Install
  command: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  args:
    chdir: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}"
    creates: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}/composer-setup.php"
  sudo: yes
  sudo_user: "{{ server_user }}"

- name: Composer | Verify
  command: php -r "if (hash_file('SHA384', 'composer-setup.php') === '55d6ead61b29c7bdee5cccfb50076874187bd9f21f65d8991d46ec5cc90518f447387fb9f76ebae1fbbacf329e583e30') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  args:
    chdir: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}"
  sudo: yes
  sudo_user: "{{ server_user }}"

- name: Composer | Setup
  command: php composer-setup.php
  args:
    chdir: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}"
    creates: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}/composer.phar"
  sudo: yes
  sudo_user: "{{ server_user }}"    

- name: Install Yii2 dependencies 
  shell: 'php composer.phar global require "fxp/composer-asset-plugin"'
  args:
    chdir: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}"
    creates: "/home/{{ server_user }}/.composer/vendor"
  sudo: yes
  sudo_user: "{{ server_user }}"
  when: yii_git_repo is defined

- name: Install dependencies for repo and Update. This may take a while . . . . . 
  shell: "php composer.phar update -n -o --prefer-dist {{ yii_extra_flags }}"
  args:
    chdir: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}"
    creates: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}/vendor" 
  sudo: yes
  sudo_user: "{{ server_user }}"
  when: yii_git_repo is defined
  tags: update_repo

- name: Kill existing yii services
  shell: ps aux | grep yii | grep -v grep | awk '{printf(\"%s \"), $2}' | xargs kill -9
  sudo: yes
  sudo_user: "{{ server_user }}"
  tags:
    - kill_yii
    - update_repo
  
- name: Run yii server
  shell: nohup php yii serve 0.0.0.0:8080 > /tmp/yii.log 2>&1 &
  args:
    chdir: "/opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }}"
  sudo: yes
  sudo_user: "{{ server_user }}"
  tags:
    - run_yii
    - update_repo
  when: yii_git_repo is defined

- name: Add cron jobs
  cron:
    name="Start yii fw"
    special_time="reboot"
    user="{{ server_user }}"
    job="cd /opt/tinker/shared_files/yii_project/{{ yii_git_repo | basename }} && nohup php yii serve 0.0.0.0:8080 > /tmp/yii.log 2>&1 &"
  sudo: yes
  sudo_user: "{{ server_user }}"
